### ISSUE TITLE
Show all transactions in a block

### ISSUE THREAD

**Issue by peter-fu** [mvs-org/mvs-explorer-api#35]
Take block 1220175 as an example, there are 23 transactions in it, but only the first 10 are displayed.

https://explorer.mvs.org/#!/blk/1220175

**Comment by canguruhh** [comment]
This bug is related to the pagination functions. We recently added pagination to all out transaction lists. Seems like we missed to add the page controls. Thanks for your help!

**Comment by LaurentSalou** [comment]
Pushed on testnet, the block page shows a pagination if there is more than 10 transactions
It will be pushed on mainnet with supernova version
