### ISSUE TITLE
Show block age in latest blocks section

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/mvs-explorer-api#5]
The blocktime in the latest blocks section should not show the timestamps of the blocks. Instead it should show the age of the blocks in seconds. 
![image](https://user-images.githubusercontent.com/21195529/36714521-df149c00-1b92-11e8-903e-b4612f8364eb.png)

**Comment by LaurentSalou** [comment]
Changed to show the age of blocks and transactions. Only changed mvs-explorer-www, no change on the api side

![blocktime](https://user-images.githubusercontent.com/29446660/36970021-161f9cd6-20a2-11e8-889e-a432799c5504.png)
